language: cpp

matrix:
  fast_finish: true
  include:
  - os: linux
    env: PYTHON=2.7
  - os: linux
    env: PYTHON=3
  - os: osx
    env: PYTHON=3.6
  allow_failures:
  - os: osx

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9

before_install:
- |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX=g++-4.9 CC=gcc-4.9; fi
  if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "${PYTHON:0:1}" = "3" ]; then
      brew update
      brew install python3
      command curl -sSL https://rvm.io/mpapis.asc | gpg --import -;
      rvm get stable
  fi
  pip install --user --upgrade pip virtualenv
  virtualenv -p python venv
  source venv/bin/activate

install:
- |
  travis_wait travis_retry pip install -r python_bindings/requirements.txt
  travis_retry cd python_bindings && python setup.py build install && cd ..

script:
- |
  set -e
  cd python_bindings
  python setup.py test
  cd ..

cache:
  - apt
  - directories:
    - $HOME/.cache/pip

