language: cpp

matrix:
  fast_finish: true
  include:
  - os: linux
    env: PYTHON=2.7
  - os: linux
    env: PYTHON=3
  - os: osx
    env: PYTHON=3.6
  allow_failures:
  - os: osx

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9

before_install:
- |
  PIP=pip
  PY=python
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX=g++-4.9 CC=gcc-4.9; fi
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew update
    brew install gcc
    PIP=pip2
    PY=python2
    if  [ "${PYTHON:0:1}" = "3" ]; then
      brew upgrade python
      brew install sashkab/python/python$PYTHON
      PIP=pip3
      PY=python3
    fi
  fi
  $PIP install --user virtualenv
  virtualenv -p $PY venv
  source venv/bin/activate
  $PIP install --upgrade pip
  $PIP install -qq setuptools

install:
- |
  travis_wait travis_retry $PIP install -r python_bindings/requirements.txt
  travis_retry cd python_bindings && $PY setup.py build install && cd ..

script:
- $PY --version
- $PIP --version
- |
  set -e
  cd python_bindings
  $PY setup.py test
  cd ..

cache:
  - apt
  - directories:
    - $HOME/.cache/pip

